var res = {
    HelloWorld_png : "res/HelloWorld.png",
    CloseNormal_png : "res/CloseNormal.png",
    CloseSelected_png : "res/CloseSelected.png",
    boton_jugar_png : "res/boton_jugar.png",
    menu_titulo_png : "res/menu_titulo.png",
    tiles32_png: "res/tiles32.png",
    mapa1_tmx: "res/mapa1.tmx",
    mapa2_tmx: "res/mapa2.tmx",
    mapaNSM1_tmx: "res/mapaNSM1.tmx",
    mapaNSM2_tmx: "res/mapaNSM2.tmx",
    moneda_png : "res/moneda.png",
    moneda_plist : "res/moneda.plist",
    jugador_avanzando_png : "res/jugador_avanzando.png",
    jugador_avanzando_plist : "res/jugador_avanzando.plist",
    jugador_subiendo_png : "res/jugador_subiendo.png",
    jugador_subiendo_plist : "res/jugador_subiendo.plist",
    boton_saltar_png: "res/boton_saltar.png",
    animacion_cuervo_png: "res/animacion_cuervo.png",
    animacion_cuervo_plist: "res/animacion_cuervo.plist",
    boton_siguiente_png : "res/boton_siguiente.png" ,
    boton_reanudar_png : "res/boton_reanudar.png",
    boton_turbo_png : "res/boton_turbo.png",
    boton_disparar_png : "res/boton_disparar.png",
    boton_nivel1_png : "res/boton_nivel1.png",
    boton_nivel2_png : "res/boton_nivel2.png",
    boton_plataformas_png : "res/boton_plataformas.png",
    boton_infinite_png : "res/boton_infinite.png",
    disparo_plist : "res/disparo.plist",
    planta_png : "res/planta.png",
    animacion_planta_plist : "res/planta.plist",
    playerrunright_png : "res/playerrunright.png",
    playerrunright_plist : "res/playerrunright.plist",
    playerjumpright_png : "res/playerjumpright.png",
    playerjumpright_plist : "res/playerjumpright.plist",
    playeridleright_png : "res/playeridleright.png",
    playeridleright_plist : "res/playeridleright.plist",
    playerdieright_png : "res/playerdieright.png",
    playerdieright_plist : "res/playerdieright.plist",
    disparo_png : "res/disparo.png",
    playershootright_png : "res/playershootright.png",
    playershootright_plist : "res/playershootright.plist",
    mario_fuego_caminar_png : "res/mario_fuego_caminar.png",
    mario_fuego_caminar_plist : "res/mario_fuego_caminar.plist",
    mario_fuego_saltar_png : "res/mario_fuego_saltar.png",
    mario_fuego_saltar_plist : "res/mario_fuego_saltar.plist",
    mario_grande_caminar_png : "res/mario_grande_caminar.png",
    mario_grande_caminar_plist : "res/mario_grande_caminar.plist",
    mario_grande_saltar_png : "res/mario_grande_saltar.png",
    mario_grande_saltar_plist : "res/mario_grande_saltar.plist",
    mario_mini_caminar_png : "res/mario_mini_caminar.png",
    mario_mini_caminar_plist : "res/mario_mini_caminar.plist",
    mario_mini_saltar_png : "res/mario_mini_saltar.png",
    mario_mini_saltar_plist : "res/mario_mini_saltar.plist",
    mario_mini_caminando_png : "res/mario_mini_caminando.png",
    mario_mini_caminando_plist : "res/mario_mini_caminando.plist",
    mario_mini_saltando_png : "res/mario_mini_saltando.png",
    mario_mini_saltando_plist : "res/mario_mini_saltando.plist",
    fondo_nsm_png: "res/FondoNSM.png",
    champiñon_png: "res/champiñon.png",
    champiñon_plist: "res/champiñon.plist",
    tortuga_png: "res/tortuga.png",
    tortuga_plist: "res/tortuga.plist",
    powerup_png: "res/PowerUp.png",
    powerup_plist: "res/PowerUp.plist",
    powerup_fuego_png: "res/PowerUpFuego.png",
    powerup_fuego_plist: "res/PowerUpFuego.plist",
    power_up_tubo_wav: "res/PowerUp_Tubo.wav",
    mario_music_bucle_wav: "res/MarioMusicBucle.wav",
    win_wav: "res/Win.wav",
    boss_music_bucle_wav: "res/BossMusicBucle.wav",
    lost_wav: "res/Lost.wav",
    boss_png: "res/boss.png",
    boss_plist: "res/boss.plist"



};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}